apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    tier: database
spec:
  type: clusterIP
  selector:
    app: mongo
    tier: database
  ports:
  - port: 27017
    targetPort: 27017
